name: record_windows
description: Windows specific implementation for record package called by record_platform_interface.
version: 0.3.0
homepage: https://github.com/llfbandit/record/tree/master/record_windows

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  record_platform_interface: ^0.3.0

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: RecordWindowsPlugin
