name: record_web
description: Web specific implementation for record package called by record_platform_interface.
version: 0.3.0
homepage: https://github.com/llfbandit/record/tree/master/record_web

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  record_platform_interface: ^0.3.0

dev_dependencies:
flutter:
  plugin:
    platforms:
      web:
        pluginClass: RecordPluginWeb
        fileName: 'record_web.dart'
