name: record_web
description: Record web implementation.
version: 0.1.0
homepage: https://github.com/llfbandit/record/tree/master/record_web

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  record_platform_interface: #^0.1.0
    path: ../record_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: RecordPluginWeb
        fileName: 'record_web.dart'
