name: record_example
description: Demonstrates how to use the record plugin.
version: 1.0.0

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.0.2"

dependencies:
  path_provider: ^2.0.1
  audioplayers: ^1.0.0-rc.2

  flutter:
    sdk: flutter

  record:
    path: ../

dev_dependencies:
  flutter_lints: ^1.0.4


# The following section is specific to Flutter.
flutter:
  uses-material-design: true
